# Generated by Django 3.0.8 on 2020-07-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200717_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/static/shared/image/default_food.jpg', null=True, upload_to='images'),
        ),
    ]
