# Generated by Django 3.0.8 on 2020-07-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to='blog/images'),
        ),
    ]
