# Generated by Django 3.0.8 on 2020-07-17 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20200708_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='address',
            field=models.CharField(default='대전', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='latitude',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='longtitude',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
