# Generated by Django 3.0.8 on 2020-07-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200717_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default='image/default.jpg', upload_to='images'),
        ),
    ]
